package com.poly.Entity;
// Generated Oct 6, 2020, 8:38:42 AM by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * FoodBillDetail generated by hbm2java
 */
@Entity
@Table(name = "FoodBillDetail", schema = "dbo", catalog = "MovieManagement")
public class FoodBillDetail implements java.io.Serializable {

	private Integer foodBillDetail;
	private Integer ticketId;
	private Integer foodId;
	private Integer quantity;
	private Double total;

	public FoodBillDetail() {
	}

	public FoodBillDetail(Integer ticketId, Integer foodId, Integer quantity, Double total) {
		this.ticketId = ticketId;
		this.foodId = foodId;
		this.quantity = quantity;
		this.total = total;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "foodBillDetail", unique = true, nullable = false)
	public Integer getFoodBillDetail() {
		return this.foodBillDetail;
	}

	public void setFoodBillDetail(Integer foodBillDetail) {
		this.foodBillDetail = foodBillDetail;
	}

	@Column(name = "ticketId")
	public Integer getTicketId() {
		return this.ticketId;
	}

	public void setTicketId(Integer ticketId) {
		this.ticketId = ticketId;
	}

	@Column(name = "foodId")
	public Integer getFoodId() {
		return this.foodId;
	}

	public void setFoodId(Integer foodId) {
		this.foodId = foodId;
	}

	@Column(name = "quantity")
	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	@Column(name = "total", precision = 53, scale = 0)
	public Double getTotal() {
		return this.total;
	}

	public void setTotal(Double total) {
		this.total = total;
	}

}
