package com.poly.Entity;
// Generated Oct 6, 2020, 8:38:42 AM by Hibernate Tools 5.1.10.Final

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Member generated by hbm2java
 */
@Entity
@Table(name = "Member", schema = "dbo", catalog = "MovieManagement")
public class Member implements java.io.Serializable {

	private Integer memberId;
	private Serializable memberName;
	private String email;
	private String password;
	private String phone;
	private Serializable address;
	private Serializable birthday;
	private Integer idCard;
	private Double totalMoney;

	public Member() {
	}

	public Member(Serializable memberName, String email, String password, String phone, Serializable address,
			Serializable birthday, Integer idCard, Double totalMoney) {
		this.memberName = memberName;
		this.email = email;
		this.password = password;
		this.phone = phone;
		this.address = address;
		this.birthday = birthday;
		this.idCard = idCard;
		this.totalMoney = totalMoney;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "memberId", unique = true, nullable = false)
	public Integer getMemberId() {
		return this.memberId;
	}

	public void setMemberId(Integer memberId) {
		this.memberId = memberId;
	}

	@Column(name = "memberName")
	public Serializable getMemberName() {
		return this.memberName;
	}

	public void setMemberName(Serializable memberName) {
		this.memberName = memberName;
	}

	@Column(name = "email")
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "password")
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "phone", length = 11)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "address")
	public Serializable getAddress() {
		return this.address;
	}

	public void setAddress(Serializable address) {
		this.address = address;
	}

	@Column(name = "birthday")
	public Serializable getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Serializable birthday) {
		this.birthday = birthday;
	}

	@Column(name = "idCard")
	public Integer getIdCard() {
		return this.idCard;
	}

	public void setIdCard(Integer idCard) {
		this.idCard = idCard;
	}

	@Column(name = "totalMoney", precision = 53, scale = 0)
	public Double getTotalMoney() {
		return this.totalMoney;
	}

	public void setTotalMoney(Double totalMoney) {
		this.totalMoney = totalMoney;
	}

}
