package com.poly.Entity;
// Generated Oct 6, 2020, 8:38:42 AM by Hibernate Tools 5.1.10.Final

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Movie generated by hbm2java
 */
@Entity
@Table(name = "Movie", schema = "dbo", catalog = "MovieManagement")
public class Movie implements java.io.Serializable {

	private Integer movieId;
	private Serializable movieName;
	private Integer duration;
	private Serializable description;
	private String thumbnail;
	private Serializable actors;
	private Serializable director;
	private Integer ageLimit;
	private Integer status;

	public Movie() {
	}

	public Movie(Serializable movieName, Integer duration, Serializable description, String thumbnail,
			Serializable actors, Serializable director, Integer ageLimit, Integer status) {
		this.movieName = movieName;
		this.duration = duration;
		this.description = description;
		this.thumbnail = thumbnail;
		this.actors = actors;
		this.director = director;
		this.ageLimit = ageLimit;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "movieId", unique = true, nullable = false)
	public Integer getMovieId() {
		return this.movieId;
	}

	public void setMovieId(Integer movieId) {
		this.movieId = movieId;
	}

	@Column(name = "movieName")
	public Serializable getMovieName() {
		return this.movieName;
	}

	public void setMovieName(Serializable movieName) {
		this.movieName = movieName;
	}

	@Column(name = "duration")
	public Integer getDuration() {
		return this.duration;
	}

	public void setDuration(Integer duration) {
		this.duration = duration;
	}

	@Column(name = "description")
	public Serializable getDescription() {
		return this.description;
	}

	public void setDescription(Serializable description) {
		this.description = description;
	}

	@Column(name = "thumbnail")
	public String getThumbnail() {
		return this.thumbnail;
	}

	public void setThumbnail(String thumbnail) {
		this.thumbnail = thumbnail;
	}

	@Column(name = "actors")
	public Serializable getActors() {
		return this.actors;
	}

	public void setActors(Serializable actors) {
		this.actors = actors;
	}

	@Column(name = "director")
	public Serializable getDirector() {
		return this.director;
	}

	public void setDirector(Serializable director) {
		this.director = director;
	}

	@Column(name = "ageLimit")
	public Integer getAgeLimit() {
		return this.ageLimit;
	}

	public void setAgeLimit(Integer ageLimit) {
		this.ageLimit = ageLimit;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

}
