package com.poly.Entity;
// Generated Oct 6, 2020, 8:38:42 AM by Hibernate Tools 5.1.10.Final

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Period generated by hbm2java
 */
@Entity
@Table(name = "Period", schema = "dbo", catalog = "MovieManagement")
public class Period implements java.io.Serializable {

	private Integer periodId;
	private String startTime;
	private Serializable dayOfWeek;
	private Double price;

	public Period() {
	}

	public Period(String startTime, Serializable dayOfWeek, Double price) {
		this.startTime = startTime;
		this.dayOfWeek = dayOfWeek;
		this.price = price;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "periodId", unique = true, nullable = false)
	public Integer getPeriodId() {
		return this.periodId;
	}

	public void setPeriodId(Integer periodId) {
		this.periodId = periodId;
	}

	@Column(name = "startTime")
	public String getStartTime() {
		return this.startTime;
	}

	public void setStartTime(String startTime) {
		this.startTime = startTime;
	}

	@Column(name = "dayOfWeek")
	public Serializable getDayOfWeek() {
		return this.dayOfWeek;
	}

	public void setDayOfWeek(Serializable dayOfWeek) {
		this.dayOfWeek = dayOfWeek;
	}

	@Column(name = "price", precision = 53, scale = 0)
	public Double getPrice() {
		return this.price;
	}

	public void setPrice(Double price) {
		this.price = price;
	}

}
