package com.poly.Entity;
// Generated Oct 6, 2020, 8:38:42 AM by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Ticket generated by hbm2java
 */
@Entity
@Table(name = "Ticket", schema = "dbo", catalog = "MovieManagement")
public class Ticket implements java.io.Serializable {

	private Integer ticketId;
	private Integer showTimeId;
	private Integer periodId;
	private Integer roomId;
	private Integer cinemaId;
	private Integer ticketQuantity;
	private Integer memberId;
	private Double ticketPriceAmount;
	private Integer ticketCodeId;
	private String code;
	private Double total;

	public Ticket() {
	}

	public Ticket(Integer showTimeId, Integer periodId, Integer roomId, Integer cinemaId, Integer ticketQuantity,
			Integer memberId, Double ticketPriceAmount, Integer ticketCodeId, String code, Double total) {
		this.showTimeId = showTimeId;
		this.periodId = periodId;
		this.roomId = roomId;
		this.cinemaId = cinemaId;
		this.ticketQuantity = ticketQuantity;
		this.memberId = memberId;
		this.ticketPriceAmount = ticketPriceAmount;
		this.ticketCodeId = ticketCodeId;
		this.code = code;
		this.total = total;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ticketId", unique = true, nullable = false)
	public Integer getTicketId() {
		return this.ticketId;
	}

	public void setTicketId(Integer ticketId) {
		this.ticketId = ticketId;
	}

	@Column(name = "showTimeId")
	public Integer getShowTimeId() {
		return this.showTimeId;
	}

	public void setShowTimeId(Integer showTimeId) {
		this.showTimeId = showTimeId;
	}

	@Column(name = "periodId")
	public Integer getPeriodId() {
		return this.periodId;
	}

	public void setPeriodId(Integer periodId) {
		this.periodId = periodId;
	}

	@Column(name = "roomId")
	public Integer getRoomId() {
		return this.roomId;
	}

	public void setRoomId(Integer roomId) {
		this.roomId = roomId;
	}

	@Column(name = "cinemaId")
	public Integer getCinemaId() {
		return this.cinemaId;
	}

	public void setCinemaId(Integer cinemaId) {
		this.cinemaId = cinemaId;
	}

	@Column(name = "ticketQuantity")
	public Integer getTicketQuantity() {
		return this.ticketQuantity;
	}

	public void setTicketQuantity(Integer ticketQuantity) {
		this.ticketQuantity = ticketQuantity;
	}

	@Column(name = "memberId")
	public Integer getMemberId() {
		return this.memberId;
	}

	public void setMemberId(Integer memberId) {
		this.memberId = memberId;
	}

	@Column(name = "ticketPriceAmount", precision = 53, scale = 0)
	public Double getTicketPriceAmount() {
		return this.ticketPriceAmount;
	}

	public void setTicketPriceAmount(Double ticketPriceAmount) {
		this.ticketPriceAmount = ticketPriceAmount;
	}

	@Column(name = "ticketCodeId")
	public Integer getTicketCodeId() {
		return this.ticketCodeId;
	}

	public void setTicketCodeId(Integer ticketCodeId) {
		this.ticketCodeId = ticketCodeId;
	}

	@Column(name = "code", length = 1)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "total", precision = 53, scale = 0)
	public Double getTotal() {
		return this.total;
	}

	public void setTotal(Double total) {
		this.total = total;
	}

}
