package com.poly.Entity;
// Generated Oct 6, 2020, 8:38:42 AM by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TicketDetail generated by hbm2java
 */
@Entity
@Table(name = "TicketDetail", schema = "dbo", catalog = "MovieManagement")
public class TicketDetail implements java.io.Serializable {

	private Integer ticketDetailId;
	private Integer ticketId;
	private Integer seatId;
	private Boolean seatStatus;

	public TicketDetail() {
	}

	public TicketDetail(Integer ticketId, Integer seatId, Boolean seatStatus) {
		this.ticketId = ticketId;
		this.seatId = seatId;
		this.seatStatus = seatStatus;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ticketDetailId", unique = true, nullable = false)
	public Integer getTicketDetailId() {
		return this.ticketDetailId;
	}

	public void setTicketDetailId(Integer ticketDetailId) {
		this.ticketDetailId = ticketDetailId;
	}

	@Column(name = "ticketId")
	public Integer getTicketId() {
		return this.ticketId;
	}

	public void setTicketId(Integer ticketId) {
		this.ticketId = ticketId;
	}

	@Column(name = "seatId")
	public Integer getSeatId() {
		return this.seatId;
	}

	public void setSeatId(Integer seatId) {
		this.seatId = seatId;
	}

	@Column(name = "seatStatus")
	public Boolean getSeatStatus() {
		return this.seatStatus;
	}

	public void setSeatStatus(Boolean seatStatus) {
		this.seatStatus = seatStatus;
	}

}
